name: XaiChess2023Training
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - zlib
  - pip
  - pip:
    - numpy
    - pandas
    - chess==1.5
    - matplotlib
    - tensorflow-gpu==2.5
    - tensorflow-datasets==4.3
    - h5py==3.1
    - tqdm
    - opencv-python
